print('{:=^50}'.format(' Exe 004'))
coisa = input('Escreva algo: ')
isa = coisa.isalpha()
isd = coisa.isdigit()
isal = coisa.isalnum()
iss = coisa.isspace()
isl = coisa.islower()
isu = coisa.isupper()
ist = coisa.istitle()
print('=' * 50)
print(f'[{coisa}] é só letras? {isa}')
print(f'E só números? {isd}')
print(f'Talves letras e números? {isal}')
print(f'Em [{coisa}] só tem espaços! {iss}')
print(f'[{coisa}] esta tudo em minúsculo? {isl}')
print(f'Então ele esta todo em maiúsculo? {isu}')
print(f'Em [{coisa}] cada palavra começa com maiúscula? {ist}')
print('=' * 50) 